name: 'CogniSim GH Action'
description: 'Run a Cognisim test given an api key and a test id.'
author: 'CogniSim'

# Define your inputs here.
inputs:
  test-id:
    description: 'The test id to run.'
    required: true
  revyl-device-url:
    description: 'The Revyl device URL server to use.'
    required: false

# Define your outputs here.
outputs:
  success:
    description: 'Whether or not the test fails.'
  result:
    description: 'The result of the test.'
  report_link:
    description: 'The link to the report to view the test results.'

runs:
  using: node20
  main: dist/index.js
